spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aspectj_demo_test
    username: postgres
    password: postgres
logging:
  level:
    root: INFO
    io:
      github:
        tttol:
          aspectj: DEBUG
    com:
      zaxxer:
        hikari:
          HikariDataSource: WARN
