spring:
  datasource:
    url: # application-{env}.ymlで設定
    username: # application-{env}.ymlで設定
    password: # application-{env}.ymlで設定
logging:
  level:
    root: INFO
    io:
      github:
        tttol:
          aspectj: DEBUG
    com:
      zaxxer:
        hikari:
          HikariDataSource: WARN
